title: BFV Robot
description: bfvrobot document
theme: just-the-docs
port: 4002
url: https://github.com/BF-CAT-Team
favicon_ico: "/assets/images/logo.png"
logo: "/assets/images/logo.png"
search_enabled: true
color_scheme: robot

collections:
  tests:
    permalink: "/:collection/:path/"
    output: true

callouts:
  warning:
    title: Warning
    color: red

nav_external_links:
  - title: 官网
    url: https://bfvrobot.net

aux_links:
  "BFVRobot on GitHub":
    - "https://github.com/BF-CAT-Team"
